version: '2'
services:
    skycave:
        image: andreasmalling/dcloudarch_css-14
        ports:
            - "37123:37123"
        depends_on:
            - mongo
        links:
          - mongo
        command: daemon #-Dcpf=mongo-storage.cpf
    mongo:
        image: mongo:3.2.9
        volumes:
            - /data/db
        command: --smallfiles --noprealloc