version: '2'
services:
    skycave:
        build: .
        image: kgoyo/cave

        # Opens port for communicating with the daemon
        ports:
            - "37123:37123"

        # Dependant on the 'mongo' container running, since it's our storage
        depends_on:
            - mongo

        # Commands for our entry-point.sh
        command: daemon -Dcpf=exam-a.cpf
    mongo:
        image: henrikbaerbak/examb:v1
        # Local mount of database, so data is persistent and available between containers
        volumes:
            - /data/db
        # Mongod commands
        command: --smallfiles --noprealloc